### PR TITLE
fix: logical enforcement of `options` in `array` flag configs

### LINKED ISSUE #30: options and arrays
What if I have a flag that's an array, but has enumerated options.  Example from ui-api
`    layouttypes: flags.array({char: 'l', options: ['Compact', 'Full'], description: 'which layout' }),`
https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_resources_record_ui.htm

This throws an error if the array isn't exactly 1 of those types.  Could arrays validate instead that all the members of the array are members of the options?

### PR DESCRIPTION
**Pull request by rbergman**
Fixes #30

### CODE REVIEW

File: packages/command/src/sfdxFlags.ts [hunk 1]
```diff
@@ -115,11 +125,43 @@ function buildVersion(options?: flags.BaseBoolean<boolean>): flags.Discriminated
 
 // sfdx
 
-function buildArray<T>(options: flags.Array<T>): flags.Discriminated<flags.Array<T>> {
-  return option('array', options, val => {
-    const vals = val.split(options.delimiter || ',');
-    return options.map ? vals.map(options.map) : vals;
-  });
```
Comment (rbergman) [inline packages/command/src/sfdxFlags.ts]: This previous impl was much simpler, but didn't handle `options` (akak `enum` value constraints) in arrays and had some typing problems in tsc 3.2.2 that are fixed now.

File: packages/command/src/sfdxFlags.ts [hunk 2]
```diff
@@ -115,11 +125,43 @@ function buildVersion(options?: flags.BaseBoolean<boolean>): flags.Discriminated
...
+function buildArray(options: flags.Array): flags.Discriminated<flags.Array>;
+function buildArray<T>(options: flags.MappedArray<T>): flags.Discriminated<flags.Array<T>>;
+function buildArray<T>(options: flags.Array | flags.MappedArray<T>): flags.Discriminated<flags.Array<T>> {
+  const kind = 'array';
+  // the following branches look very similar but are typed fundamentally differently from one another, making
+  // then challenging to refine into a single implementation without applying some hard to read type abstractions
```
Comment (shetzel) [inline packages/command/src/sfdxFlags.ts]: typo --> s/then/them
